# Generated by Django 5.1.4 on 2024-12-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingredient_name',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='menu_item_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='supplier_name',
        ),
    ]
